"""empty message

Revision ID: c44b43354e00
Revises: 
Create Date: 2021-03-26 13:19:35.356503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44b43354e00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motocycles_info')
    op.drop_table('brands')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('brand_id', name='brands_pkey')
    )
    op.create_table('motocycles_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('modifications', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('year_birth', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('engine', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('horse_power', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('torque', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('cylinders', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('type_engine', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('gear_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cycle_class', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('abs', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='motocycles_info_pkey')
    )
    # ### end Alembic commands ###
