"""empty message

Revision ID: ed08a193ab42
Revises: 
Create Date: 2021-03-26 00:11:23.760794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed08a193ab42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motocycles_info', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_motocycles_info_brand_name'), 'motocycles_info', ['brand_name'], unique=False)
    op.create_foreign_key(None, 'motocycles_info', 'brands', ['brand_name'], ['brand_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motocycles_info', type_='foreignkey')
    op.drop_index(op.f('ix_motocycles_info_brand_name'), table_name='motocycles_info')
    op.alter_column('motocycles_info', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
